# Place this file in the directory one level above this current directory
version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo:3.2.6
    network_mode: host
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/mongodb:/data/db
  mongoloopbackapi:
    container_name: mongoloopbackapi
    image: mongoloopbackapi:1.0.0
    build:
      context: ./mongo-loopback-api
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "3000:3000"
    restart: always
